const NUMERO_WHATSAPP = "COLOQUE_SEU_NUMERO_AQUI";
const DIAS_ABERTOS = [0,2,3,5,6];
const HORA_ABERTURA = 4;
const HORA_FECHAMENTO = 22;
const TAXAS = {N1:4,N3:3,N5:5,C2:6};

let carrinho = carregarCarrinho();
let estoque = {};
let tipoPedido = "Entrega";
let filtroAtual = "todos";
let somenteFavoritos = false;

const cfg = window.SUPABASE_CONFIG || {};
const sb = cfg.url && cfg.key && window.supabase ? window.supabase.createClient(cfg.url,cfg.key) : null;

function moeda(v){return Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});}
function carregarCarrinho(){try{const s=JSON.parse(localStorage.getItem("cantinho_carrinho")||"[]");return Array.isArray(s)?s:[]}catch{return []}}
function salvarCarrinho(){localStorage.setItem("cantinho_carrinho",JSON.stringify(carrinho));}
function lojaAberta(){const a=new Date(),d=a.getDay(),m=a.getHours()*60+a.getMinutes();return DIAS_ABERTOS.includes(d)&&m>=HORA_ABERTURA*60&&m<HORA_FECHAMENTO*60;}
function proximaAbertura(){const a=new Date(),d=a.getDay(),m=a.getHours()*60+a.getMinutes();if(DIAS_ABERTOS.includes(d)&&m<HORA_ABERTURA*60)return "Abre hoje às 04h";const nomes=["domingo","segunda","terça","quarta","quinta","sexta","sábado"];for(let i=1;i<=7;i++){const x=(d+i)%7;if(DIAS_ABERTOS.includes(x))return `Abre ${nomes[x]} às 04h`;}return "Fechado";}
function atualizarStatus(){const box=document.getElementById("headerStatus"),txt=document.getElementById("headerStatusText");if(lojaAberta()){box?.classList.remove("closed");if(txt)txt.textContent="Aberto • fecha às 22h";}else{box?.classList.add("closed");if(txt)txt.textContent=proximaAbertura();}atualizarProdutos();atualizarBotaoWhatsApp();}
function disponivel(id){return !(id in estoque)||estoque[id]!==false;}
function setSystemMessage(t,e=false){const el=document.getElementById("stockMessage");if(!el)return;if(!t){el.className="system-message hidden";return;}el.textContent=t;el.className="system-message"+(e?" error":"");}
async function carregarEstoque(){if(!sb){setSystemMessage("Estoque online ainda não configurado.",true);atualizarProdutos();return false;}const {data,error}=await sb.from("produtos_estoque").select("produto_id,disponivel");if(error){console.error(error);setSystemMessage("Não foi possível sincronizar o estoque agora.",true);atualizarProdutos();return false;}estoque={};(data||[]).forEach(i=>estoque[i.produto_id]=i.disponivel!==false);setSystemMessage("");atualizarProdutos();atualizarCarrinho();return true;}
function atualizarProdutos(){const aberta=lojaAberta();document.querySelectorAll(".product-card").forEach(card=>{const id=card.dataset.produtoId,ok=disponivel(id),btn=card.querySelector(".add-button");card.classList.toggle("sold-out",!ok);if(!btn)return;if(!ok){btn.disabled=true;btn.textContent="Esgotado";}else if(!aberta){btn.disabled=true;btn.textContent="Loja fechada";}else{btn.disabled=false;btn.textContent="Adicionar";}});}
function adicionarProduto(id,nome,preco){if(!lojaAberta())return toast("🔴 Loja fechada no momento");if(!disponivel(id))return toast(`🔴 ${nome} está esgotado`);const item=carrinho.find(i=>i.id===id);if(item)item.qtd++;else carrinho.push({id,nome,preco:Number(preco),qtd:1});salvarCarrinho();atualizarCarrinho();toast("✅ Produto adicionado");}
function reduzirProduto(id){const item=carrinho.find(i=>i.id===id);if(!item)return;item.qtd--;if(item.qtd<=0)carrinho=carrinho.filter(i=>i.id!==id);salvarCarrinho();atualizarCarrinho();}
function removerProduto(id){carrinho=carrinho.filter(i=>i.id!==id);salvarCarrinho();atualizarCarrinho();}
function subtotal(){return carrinho.reduce((s,i)=>s+i.preco*i.qtd,0);}
function quantidade(){return carrinho.reduce((s,i)=>s+i.qtd,0);}
function taxaEntrega(){if(tipoPedido!=="Entrega")return 0;return TAXAS[document.getElementById("region")?.value]||0;}
function atualizarCarrinho(){const qtd=quantidade(),sub=subtotal();document.getElementById("headerCartCount").textContent=qtd;document.getElementById("floatingCartCount").textContent=qtd;document.getElementById("floatingCartTotal").textContent=moeda(sub);document.getElementById("cartSubtotal").textContent=moeda(sub);const lista=document.getElementById("cartList");if(!carrinho.length){lista.innerHTML='<div class="cart-empty"><div>🛒</div><strong>Seu carrinho está vazio</strong><span>Adicione produtos para começar.</span></div>';}else{lista.innerHTML=carrinho.map(item=>{const esgotado=!disponivel(item.id),safe=item.nome.replaceAll("'","");return `<article class="cart-item"><div><h4>${item.nome}</h4><small>${moeda(item.preco)} cada</small>${esgotado?'<div class="item-warning">🔴 ESGOTADO</div>':''}<div class="qty-controls"><button onclick="reduzirProduto('${item.id}')">−</button><strong>${item.qtd}</strong><button onclick="adicionarProduto('${item.id}','${safe}',${item.preco})" ${esgotado?"disabled":""}>+</button><button class="remove" onclick="removerProduto('${item.id}')">Remover</button></div></div><div class="item-price">${moeda(item.preco*item.qtd)}</div></article>`;}).join("");}atualizarResumoCheckout();}
function abrirCarrinho(){document.getElementById("cartDrawer").classList.add("active");document.body.style.overflow="hidden";}
function fecharCarrinho(){document.getElementById("cartDrawer").classList.remove("active");document.body.style.overflow="";}
async function abrirCheckout(){if(!lojaAberta())return toast("🔴 A loja está fechada");if(!carrinho.length)return toast("Adicione algum produto primeiro");await carregarEstoque();const esg=carrinho.filter(i=>!disponivel(i.id));if(esg.length){alert("Produtos esgotados:\n\n"+esg.map(i=>"• "+i.nome).join("\n"));return;}fecharCarrinho();document.getElementById("checkoutModal").classList.add("active");document.body.style.overflow="hidden";atualizarResumoCheckout();}
function fecharCheckout(){document.getElementById("checkoutModal").classList.remove("active");document.body.style.overflow="";}
function selecionarTipo(tipo){tipoPedido=tipo;document.getElementById("deliveryBtn").classList.toggle("active",tipo==="Entrega");document.getElementById("pickupBtn").classList.toggle("active",tipo==="Retirada");document.getElementById("regionField").classList.toggle("hidden",tipo==="Retirada");document.getElementById("addressField").classList.toggle("hidden",tipo==="Retirada");if(tipo==="Retirada"){document.getElementById("region").value="";document.getElementById("address").value="";}atualizarResumoCheckout();}
function atualizarResumoCheckout(){const sub=subtotal(),tx=taxaEntrega();document.getElementById("checkoutSubtotal").textContent=moeda(sub);document.getElementById("checkoutFee").textContent=moeda(tx);document.getElementById("checkoutTotal").textContent=moeda(sub+tx);atualizarBotaoWhatsApp();}
function atualizarBotaoWhatsApp(){const btn=document.getElementById("sendWhatsApp");if(!btn)return;btn.disabled=!lojaAberta();btn.textContent=lojaAberta()?"💬 Enviar pedido pelo WhatsApp":"🔒 Loja fechada";}
function favoritos(){try{return JSON.parse(localStorage.getItem("cantinho_favoritos")||"[]")}catch{return []}}
function toggleFavorito(btn,id){let f=favoritos();f=f.includes(id)?f.filter(x=>x!==id):[...f,id];localStorage.setItem("cantinho_favoritos",JSON.stringify(f));restaurarFavoritos();aplicarFiltros();}
function restaurarFavoritos(){const f=favoritos();document.querySelectorAll(".product-card").forEach(card=>{const btn=card.querySelector(".heart"),ativo=f.includes(card.dataset.produtoId);btn.classList.toggle("active",ativo);btn.textContent=ativo?"♥":"♡";});}
function mostrarFavoritos(){somenteFavoritos=!somenteFavoritos;document.querySelectorAll(".round-button").forEach(b=>b.classList.toggle("active",somenteFavoritos));aplicarFiltros();toast(somenteFavoritos?"Mostrando favoritos":"Mostrando todo o cardápio");rolarCardapio();}
function syncSearchInputs(source){const v=source.value;if(source.id==="searchDesktop")document.getElementById("searchMobile").value=v;else document.getElementById("searchDesktop").value=v;aplicarFiltros();}
function aplicarFiltros(){const termo=document.getElementById("searchDesktop").value.toLowerCase().trim(),f=favoritos();let n=0;document.querySelectorAll(".product-card").forEach(card=>{const c=filtroAtual==="todos"||card.dataset.category===filtroAtual;const texto=(card.dataset.name+" "+card.innerText).toLowerCase();const b=!termo||texto.includes(termo);const fav=!somenteFavoritos||f.includes(card.dataset.produtoId);const show=c&&b&&fav;card.classList.toggle("hidden-card",!show);if(show)n++;});document.getElementById("emptySearch").classList.toggle("hidden",n!==0);}
function filtrarCategoria(cat){filtroAtual=cat;document.querySelectorAll(".category").forEach(b=>b.classList.toggle("active",b.dataset.filter===cat));aplicarFiltros();rolarCardapio();}
function limparFiltros(){filtroAtual="todos";somenteFavoritos=false;document.getElementById("searchDesktop").value="";document.getElementById("searchMobile").value="";document.querySelectorAll(".category").forEach(b=>b.classList.toggle("active",b.dataset.filter==="todos"));document.querySelectorAll(".round-button").forEach(b=>b.classList.remove("active"));aplicarFiltros();}
function buscarProduto(t){filtroAtual="todos";document.getElementById("searchDesktop").value=t;document.getElementById("searchMobile").value=t;aplicarFiltros();rolarCardapio();}
function rolarCardapio(){document.getElementById("cardapio").scrollIntoView({behavior:"smooth",block:"start"});}
function formatarTelefone(){const campo=document.getElementById("customerPhone");campo.addEventListener("input",()=>{let v=campo.value.replace(/\D/g,"").slice(0,11);if(v.length>10)v=v.replace(/^(\d{2})(\d{5})(\d{4})$/,"($1) $2-$3");else if(v.length>6)v=v.replace(/^(\d{2})(\d{4})(\d{0,4})$/,"($1) $2-$3");else if(v.length>2)v=v.replace(/^(\d{2})(\d+)/,"($1) $2");campo.value=v;});}
async function finalizarPedido(){if(!lojaAberta())return alert("A loja está fechada.");if(!carrinho.length)return alert("Seu carrinho está vazio.");const ok=await carregarEstoque();if(sb&&!ok)return alert("Não foi possível confirmar o estoque.");const esg=carrinho.filter(i=>!disponivel(i.id));if(esg.length)return alert("Produtos esgotados:\n\n"+esg.map(i=>"• "+i.nome).join("\n"));const nome=document.getElementById("customerName").value.trim(),tel=document.getElementById("customerPhone").value.trim(),reg=document.getElementById("region").value,end=document.getElementById("address").value.trim(),pag=document.getElementById("payment").value,troco=document.getElementById("changeFor").value.trim(),obs=document.getElementById("notes").value.trim();if(!nome)return alert("Digite seu nome.");if(!tel)return alert("Digite seu telefone.");if(tipoPedido==="Entrega"&&!reg)return alert("Selecione sua região.");if(tipoPedido==="Entrega"&&!end)return alert("Digite o endereço.");if(!pag)return alert("Selecione a forma de pagamento.");if(NUMERO_WHATSAPP==="COLOQUE_SEU_NUMERO_AQUI")return alert("Configure o número do WhatsApp no começo do script.js.");const sub=subtotal(),tx=taxaEntrega(),total=sub+tx;let msg="🍕 *NOVO PEDIDO - CANTINHO PIZZA BURGUER*\n\n";msg+=`👤 *Cliente:* ${nome}\n📱 *Telefone:* ${tel}\n📦 *Recebimento:* ${tipoPedido}\n`;if(tipoPedido==="Entrega")msg+=`🗺️ *Região:* ${reg}\n📍 *Endereço:* ${end}\n`;msg+="\n🧾 *ITENS DO PEDIDO*\n━━━━━━━━━━━━━━\n";carrinho.forEach(i=>msg+=`\n${i.qtd}x ${i.nome}\n${moeda(i.preco*i.qtd)}\n`);msg+=`\n━━━━━━━━━━━━━━\n💵 *Subtotal:* ${moeda(sub)}\n`;if(tipoPedido==="Entrega")msg+=`🛵 *Taxa (${reg}):* ${moeda(tx)}\n`;msg+=`💰 *TOTAL:* ${moeda(total)}\n\n💳 *Pagamento:* ${pag}\n`;if(pag==="Dinheiro"&&troco)msg+=`💵 *Troco para:* ${troco}\n`;if(obs)msg+=`\n📝 *Observações:*\n${obs}\n`;window.open(`https://wa.me/${NUMERO_WHATSAPP}?text=${encodeURIComponent(msg)}`,"_blank");}
function toast(t){const x=document.getElementById("toast");x.textContent=t;x.classList.add("active");clearTimeout(window._toast);window._toast=setTimeout(()=>x.classList.remove("active"),1800);}
function iniciarRealtime(){if(!sb)return;sb.channel("estoque-site").on("postgres_changes",{event:"*",schema:"public",table:"produtos_estoque"},p=>{if(p.new?.produto_id)estoque[p.new.produto_id]=p.new.disponivel!==false;if(p.eventType==="DELETE"&&p.old?.produto_id)delete estoque[p.old.produto_id];atualizarProdutos();atualizarCarrinho();}).subscribe();}
document.addEventListener("DOMContentLoaded",async()=>{document.querySelectorAll(".category").forEach(btn=>btn.addEventListener("click",()=>{filtroAtual=btn.dataset.filter;document.querySelectorAll(".category").forEach(x=>x.classList.remove("active"));btn.classList.add("active");aplicarFiltros();}));document.getElementById("searchDesktop").addEventListener("input",e=>syncSearchInputs(e.target));document.getElementById("searchMobile").addEventListener("input",e=>syncSearchInputs(e.target));document.getElementById("region").addEventListener("change",atualizarResumoCheckout);document.getElementById("payment").addEventListener("change",()=>{const dinheiro=document.getElementById("payment").value==="Dinheiro";document.getElementById("changeField").classList.toggle("hidden",!dinheiro);if(!dinheiro)document.getElementById("changeFor").value="";});formatarTelefone();restaurarFavoritos();atualizarStatus();atualizarCarrinho();aplicarFiltros();await carregarEstoque();iniciarRealtime();setInterval(atualizarStatus,30000);setInterval(carregarEstoque,60000);});
