insert into public.produtos_estoque (produto_id,nome,disponivel)
values
('x-salada','X-Salada',true),
('x-burguer','X-Burguer',true),
('x-bacon','X-Bacon',true),
('x-tudao','X-Tudão',true),
('x-tudo','X-Tudo',true),
('moda-da-casa','Moda da Casa',true),
('artesanal-simples','Hambúrguer Simples',true),
('x-calabresa-artesanal','X Calabresa Artesanal',true),
('x-bacon-artesanal','X Bacon Artesanal',true),
('pizza-mucarela','Pizza Muçarela',true),
('pizza-calabresa','Pizza Calabresa',true),
('pizza-frango','Pizza de Frango',true),
('pizza-portuguesa','Pizza Portuguesa',true),
('pizza-baiana','Pizza Baiana',true),
('pizza-milho','Pizza de Milho',true),
('calzone-calabresa','Calzone de Calabresa',true),
('calzone-frango','Calzone de Frango',true),
('calzone-presunto','Calzone de Presunto',true),
('coca-lata-zero','Coca-Cola Lata Sem Açúcar',true),
('coca-2l','Coca-Cola 2L',true),
('coca-zero-2l','Coca-Cola Sem Açúcar 2L',true),
('guarana-1l','Guaraná Antarctica 1L',true),
('pepsi-1l','Pepsi 1L',true),
('refri-guarana','Refri Guaraná',true),
('refri-laranja','Refri Laranja',true),
('refri-cola','Refri Cola',true)
on conflict (produto_id) do update set nome=excluded.nome;
